### ISSUE TITLE
Consider adding map header file

### ISSUE THREAD

**Issue by NY00123** [FrenkelS/keensource456tandy#18]
Since other headers were added, I suppose that the map header file (internally named MTEMP.TMP by TED5) can also be.

**Comment by NY00123** [comment]
Here's another late realization of mine. New audio and graphics files are included in the released ZIPs out of necessity, say due to the new Tandy music or the ZX0 compression. But the map data has needed no change so far, which must explain the lack of the inclusion of a map header.

I'll keep the issue opened for now, say, in case there's a need to change the map data in the future.

**Comment by FrenkelS** [comment]
That's exactly the reason why I haven't added the map header file.

I've compressed the maps with ZX0. GAMEMAPS.CK4 is now 60 kB instead of 97 kB. 
But somehow there's now some memory corruption. The game looks fine, but the demo crashes when it tries to play the second level. I'm probably doing something wrong with pointers.

**Comment by FrenkelS** [comment]
It's fixed. There was a bug in my tool that creates GAMEMAPS.CK4.

MAPHEAD.CK4 is added to the repository and GAMEMAPS.CK4 is included in the release files.
